# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/irene/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12672-DESKTOP-2UOKUU8/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.cache/wt [current_project]
set_property parent.project_path C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sim_1/new/tfg_irene_package.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sim_1/new/CONV.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/GEN1.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/GEN2.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/GEN3.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/GEN4.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/INTERFAZ_ET1.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/INTERFAZ_ET2.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/INTERFAZ_ET3.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sim_1/new/MAXPOOL.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/MUX.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/MUX2.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/MUX3.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/PAR2SER.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sim_1/new/RELU.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_1.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_10.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_11.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_12.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_13.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_14.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_15.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_16.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_2.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_3.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_4.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_5.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_6.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_7.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_8.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM1_9.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_1.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_10.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_11.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_12.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_13.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_14.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_15.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_16.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_17.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_18.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_19.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_2.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_20.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_3.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_4.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_5.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_6.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_7.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_8.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM2_9.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_1.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_10.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_11.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_12.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_13.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_14.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_15.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_16.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_17.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_18.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_19.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_2.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_20.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_3.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_4.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_5.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_6.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_7.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_8.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/ROM3_9.vhd
  C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/new/SISTEMA_COMPLETO.vhd
}
read_ip -quiet C:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all c:/Users/irene/Desktop/TFG/RED_CONVNETJS/RED_CONVNETJS.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top SISTEMA_COMPLETO -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SISTEMA_COMPLETO.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SISTEMA_COMPLETO_utilization_synth.rpt -pb SISTEMA_COMPLETO_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
